function Hd = BandStopleastsquar
%BANDSTOPLEASTSQUAR Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.3 and Signal Processing Toolbox 7.5.
% Generated on: 03-May-2020 18:41:14

% FIR least-squares Bandstop filter designed using the FIRLS function.

% All frequency values are in Hz.
Fs = 16000;  % Sampling Frequency

N      = 150;   % Order
Fpass1 = 2000;  % First Passband Frequency
Fstop1 = 2500;  % First Stopband Frequency
Fstop2 = 3500;  % Second Stopband Frequency
Fpass2 = 4000;  % Second Passband Frequency
Wpass1 = 1;     % First Passband Weight
Wstop  = 100;   % Stopband Weight
Wpass2 = 1;     % Second Passband Weight

% Calculate the coefficients using the FIRLS function.
b  = firls(N, [0 Fpass1 Fstop1 Fstop2 Fpass2 Fs/2]/(Fs/2), [1 1 0 0 1 ...
           1], [Wpass1 Wstop Wpass2]);
Hd = dfilt.dffir(b);

% [EOF]
