function Hd = BandStopIIR
%BANDSTOPIIR Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.3 and Signal Processing Toolbox 7.5.
% Generated on: 03-May-2020 19:47:08

% Elliptic Bandstop filter designed using FDESIGN.BANDSTOP.

% All frequency values are in Hz.
Fs = 100000;  % Sampling Frequency

Fpass1 = 15000;   % First Passband Frequency
Fstop1 = 20000;   % First Stopband Frequency
Fstop2 = 25000;   % Second Stopband Frequency
Fpass2 = 30000;   % Second Passband Frequency
Apass1 = 0.2;     % First Passband Ripple (dB)
Astop  = 40;      % Stopband Attenuation (dB)
Apass2 = 0.2;     % Second Passband Ripple (dB)
match  = 'both';  % Band to match exactly

% Construct an FDESIGN object and call its ELLIP method.
h  = fdesign.bandstop(Fpass1, Fstop1, Fstop2, Fpass2, Apass1, Astop, ...
                      Apass2, Fs);
Hd = design(h, 'ellip', 'MatchExactly', match);

% [EOF]
