function Hd = HighPass_butterworth
%HIGHPASS_BUTTERWORTH Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.3 and Signal Processing Toolbox 7.5.
% Generated on: 03-May-2020 19:33:07

% Butterworth Highpass filter designed using FDESIGN.HIGHPASS.

% All frequency values are in Hz.
Fs = 16000;  % Sampling Frequency

Fstop = 5800;        % Stopband Frequency
Fpass = 5900;        % Passband Frequency
Astop = 80;          % Stopband Attenuation (dB)
Apass = 3;           % Passband Ripple (dB)
match = 'stopband';  % Band to match exactly

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.highpass(Fstop, Fpass, Astop, Apass, Fs);
Hd = design(h, 'butter', 'MatchExactly', match);

% [EOF]
